### ISSUE TITLE
Python client won't connect to hololens

### ISSUE THREAD

**Issue by roejanse** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#1]
Hi,

I'm trying to get this to work, but when I run the python client, I get a TimeOutError on the socket.connect. I've setup the Unity solution according to the steps in the readme and verified that the capabilities mentioned are checked (in the built solution also).

I've set the HOST variable in the python script to the ip of the hololens in my local network.
I've set my firewall to accept all traffic to that ip address.

Can you help me find out what I'm missing here?
Thanks!

**Comment by cgsaxner** [comment]
Hi,
sorry that the connection is not working for you. Could you please try to verify that the socket has been properly opened on the HoloLens side. 
To do this: 
1. Connect the HoloLens to the same network as your PC running the client
2. Build and deploy the "UnityHL2RmStreamer" app to your HoloLens. Note that when the plugin starts, you should get a message like "Streamer::StartServer: Server is listening at 23940" in the Visual Studio Output window.
3. Now, you have various options to check whether the ports have correctly been opened. 
   1. You can use `Test-NetConnection` in Windows PowerShell to determine whether the ports have been opened. To do this, run 
`Test-NetConnection -Port 23940 -ComputerName <IP_of_your_HL> -InformationLevel Detailed` 
If the TCP port is open and ou should get an output like this:
![image](https://user-images.githubusercontent.com/29651139/106895934-29d66500-66f1-11eb-865a-16cfdbde8442.png)
   2. You can install [PortQry](https://www.microsoft.com/en-us/download/details.aspx?id=17148) from Microsoft, then use the Command Promt to run
    `portqry -n <IP_of_your_HL>` or `portqry -n <IP_of_your_HL> -p tcp -e 23940`
which should show you that the port is listening:
![image](https://user-images.githubusercontent.com/29651139/106896704-3c04d300-66f2-11eb-95ae-1c2007825786.png)
    - Listening means the server is listening on the specified port, which means that the connection should be possible and there is likely something wrong with the python client.
    - Filtered means it received a TCP acknowledgement packet with the Reset flag set which likely indicates a firewall issue.
    - Not Listening means it didn't receive a response at all, which probably means that the port has not been opened on the HL side, because the app did not deploy correctly.

**Comment by roejanse** [comment]
Thanks, I got it to work now. :)
It seemed the deploy hadn't gone right the first time.
