### ISSUE TITLE
How to call this plug-in in a C++ program

### ISSUE THREAD

**Issue by Lancename** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#11]
Hello, the instructions explain how to use this plug-in in Unity's C#. But I need to use this plug-in in other C++ (WIN RT), can you give me some help? I found that it seems impossible to use the LoadLibrary function in UWP to load DLL files, and it always prompts that LoadLibrary does not exist.

**Comment by cgsaxner** [comment]
Hi @Lancename, for using the code directly in C++/WinRT, you do not need a Plug-In. It should be possible to add the .h and .cpp files directly to the C++/WinRT project and call the classes / function from there.
The official [HoloLens2ForCV repo](https://github.com/microsoft/HoloLens2ForCV/tree/main/Samples/StreamRecorder) contains pure C++ apps, maybe you find the samples there useful.

**Comment by Lancename** [comment]
@Lancename thank you！，I will try it.
