### ISSUE TITLE
I want to add another ports to transform the data from Hololens2 to PC

### ISSUE THREAD

**Issue by daijava666** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#12]
Hi cgsaxner,
     I'm sorry to disturb you, but I have some questions to ask you. I would be very grateful if you can help me answer.
     1. I'm using this part of your code, and I want to add some ports for TCP/IP to tarnsform the data from Hololens2 to PC. But in addition to the two ports 23940 and 23941, no one can be added for communiction, for example, 23942.
     2. If I change 23940 and 23941 to other ports, such as 23333 or 2333. It can't establish a TCP connection with the client which written in python with you， even if the port number on both sides are the same.

**Comment by cgsaxner** [comment]
Hi @daijava666,
this is strange, as I do use additional ports with the streamer in a side project. 

If you have modified the Plugin, you can try to confirm that the port is successfully created on the HoloLens side by adding some debugging output. Then, you have several methods of confirming that the port is open and listening, as described in [this issue](https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/issues/1#issuecomment-773299012). With the tools described there, you should also be able to confirm that the ports are not blocked by your firewall, and no other connection is currently using the ports, which could also lead to isssues.

**Comment by daijava666** [comment]
Hi @cgsaxner ,
    I want to know how could I debug the program when it is put into the unity project as a plugin, and the project is deployed to Hololens. Because I want to know which part of the code has a problem.
    There is another question, the VS Output Window in the figure below refers to which project, unity or HoloLens2-Unity-ResearchModeStreamer？
    I would be grateful if you could help me answer,thank you.
    Best wishes.
![image](https://user-images.githubusercontent.com/87458007/127251903-077eca90-1ad7-46d8-bd23-3c4e0aa2d7dd.png)

**Comment by cgsaxner** [comment]
Hello @daijava666,

for debugging the C++ Plugin, you have to also build a .pdb file from the Plugin along with the .dll, and add this to the _Assets/Plugins/WSAPlayer/ARM64_ folder along with the .dll. When you build the project with Unity, make sure that "Copy pdb files" is checked, I also check "Development Build" and "Script Debugging", although I am not sure this is necessary. Then you build with Unity and open the Solution in VS. In VS, go to Debug -> Options -> General and uncheck "Enable Just My Code".
Now, when you build & deploy to the HoloLens, you should be able to debug the C++ .dll.

Also, the VS output window refers to the output you get when you build & deploy the VS solution, built by Unity (UnityHL2RmStreamer), to the HoloLens. 

Hope this could help!

**Comment by daijava666** [comment]
Hi @cgsaxner ,
Thank you for your guidance, I found the problem through debug. Because the ARM64 folder was not created in the Plugins of the unity project, the .dll could not be updated to the compiled unity project.
