### ISSUE TITLE
Long Throw Depth Image

### ISSUE THREAD

**Issue by li-mandy** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#14]
Hello, cgsaxner, thank you for your effort of this repository, it really helps my work, I have a question about receiving LT depth image instead AHAT, I changed one place in Plugin, but the image I received looks very strange, I am wondering if I need change some other places like invalidation value, could you give me some suggestions about it?

**Comment by cgsaxner** [comment]
Hi!
I'm glad you found the repository useful.
Yes, you would also need to adjust the [Streamer::Send](https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/blob/7431407b5a2433b5b04d61831f0016d63a8db54d/HL2RmStreamUnityPlugin/Streamer.cpp#L79-L223) method in the Plugin to process LT depth, as in the current implementation, the depth invalidation works only for AHAT frames. 
I would recommend taking a look at the [RMCameraReader::SaveDepth](https://github.com/microsoft/HoloLens2ForCV/blob/026a4736e2f37b5ffeae9785792b78d7f3014682/Samples/StreamRecorder/StreamRecorderApp/RMCameraReader.cpp#L277-L350) method in the StreamRecorderApp on the official [HoloLens2ForCV](https://github.com/microsoft/HoloLens2ForCV) repository, which shows how to treat AHAT and LT depth. Hope this is useful for you.

**Comment by li-mandy** [comment]
> Hi!
> I'm glad you found the repository useful.
> Yes, you would also need to adjust the [Streamer::Send](https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/blob/7431407b5a2433b5b04d61831f0016d63a8db54d/HL2RmStreamUnityPlugin/Streamer.cpp#L79-L223) method in the Plugin to process LT depth, as in the current implementation, the depth invalidation works only for AHAT frames.
> I would recommend taking a look at the [RMCameraReader::SaveDepth](https://github.com/microsoft/HoloLens2ForCV/blob/026a4736e2f37b5ffeae9785792b78d7f3014682/Samples/StreamRecorder/StreamRecorderApp/RMCameraReader.cpp#L277-L350) method in the StreamRecorderApp on the official [HoloLens2ForCV](https://github.com/microsoft/HoloLens2ForCV) repository, which shows how to treat AHAT and LT depth. Hope this is useful for you.

**Comment by li-mandy** [comment]
> > Hi!
> > I'm glad you found the repository useful.
> > Yes, you would also need to adjust the [Streamer::Send](https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/blob/7431407b5a2433b5b04d61831f0016d63a8db54d/HL2RmStreamUnityPlugin/Streamer.cpp#L79-L223) method in the Plugin to process LT depth, as in the current implementation, the depth invalidation works only for AHAT frames.
> > I would recommend taking a look at the [RMCameraReader::SaveDepth](https://github.com/microsoft/HoloLens2ForCV/blob/026a4736e2f37b5ffeae9785792b78d7f3014682/Samples/StreamRecorder/StreamRecorderApp/RMCameraReader.cpp#L277-L350) method in the StreamRecorderApp on the official [HoloLens2ForCV](https://github.com/microsoft/HoloLens2ForCV) repository, which shows how to treat AHAT and LT depth. Hope this is useful for you.

Hi, many thanks to your reply, I tried the invalidation masks for Long throw depth image, but still there is somthing strange with the received depth image like there are some rings in the image, do you have some ideas for this problem? I am not quite sure, if the thing happened because of the frame processor or maybe socket.

**Comment by OxO-7** [comment]
Hi,I have the same problem as you.There are not only strange rings in the image, but also different pixel values in different positions of the same plane, such as the screen.

**Comment by li-mandy** [comment]
> Hi,I have the same problem as you.There are not only strange rings in the image,the pixel values of the same plane, such as different positions of the screen, are also different.

I am currently focusing on that, if any progress I would update to you. :)

**Comment by cgsaxner** [comment]
Maybe you could post a screenshot of how your frames are looking right now. From what you describe, it could be a problem with byte order. The current python receiver unpacks the frames to the systems native byte order (as specified by the `@` in the `RM_STREAM_HEADER_FORMAT`, which is little endian in my case:
https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/blob/7431407b5a2433b5b04d61831f0016d63a8db54d/py/hololens2_simpleclient.py#L27
You could try to change the byte oder to little endian by hand, by replacing the `@` with `<`. But this is just a pretty wild guess.

**Comment by OxO-7** [comment]
![image](https://user-images.githubusercontent.com/69660262/126774097-9cbcb7f6-82ce-4137-8169-9d398ed7178d.png)
Like this, the right side is a flat wall

**Comment by li-mandy** [comment]
Hi, Christina,

I am also wondering the image format thing, as you can see, several received Long throw depth images.

Best wishes,
Mandy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by li-mandy** [comment]
> Maybe you could post a screenshot of how your frames are looking right now. From what you describe, it could be a problem with byte order. The current python receiver unpacks the frames to the systems native byte order (as specified by the `@` in the `RM_STREAM_HEADER_FORMAT`, which is little endian in my case:
> https://github.com/cgsaxner/HoloLens2-Unity-ResearchModeStreamer/blob/7431407b5a2433b5b04d61831f0016d63a8db54d/py/hololens2_simpleclient.py#L27
> 
> 
> You could try to change the byte oder to little endian by hand, by replacing the `@` with `<`. But this is just a pretty wild guess.




> ![image](https://user-images.githubusercontent.com/69660262/126774097-9cbcb7f6-82ce-4137-8169-9d398ed7178d.png)
> Like this, the right side is a flat wall.
> I tried your suggestion, but it didn't work

The same as yours

**Comment by li-mandy** [comment]
![image](https://user-images.githubusercontent.com/61583231/126777378-5fa72d15-25dd-49c1-b949-885c3aacbe17.png)
I changed here and now it seems better but too dark, I am not sure if it is right and why.

**Comment by li-mandy** [comment]
> ![image](https://user-images.githubusercontent.com/69660262/126774097-9cbcb7f6-82ce-4137-8169-9d398ed7178d.png)
> Like this, the right side is a flat wall.
> I tried your suggestion, but it didn't work
![image](https://user-images.githubusercontent.com/61583231/126779121-52021e9e-6bc5-4f14-94fc-2cd2cd9bddb1.png)
Try this.

**Comment by OxO-7** [comment]
It works!Thanks very much.
