### ISSUE TITLE
This Dll can not work in Hololens2 with Unity2020, but it can work With Unity2019

### ISSUE THREAD

**Issue by hanjianwei92** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#18]
Hi
     I try to run this dll with Unity2020 in Hololens2 , but it not work . Is it only run in Unity2019? How can make it work in Unity 2020. 
      I'd be grateful if you can reply.

**Comment by cgsaxner** [comment]
Hi @hanjianwei92,
I'm currently using a variant of this Plugin with Unity2020 and did not have any issues when upgrading as far as I remember. Could you be more specific about what is not working and in which part of the pipeline, e.g., the error message you receive?

**Comment by hanjianwei92** [comment]
Hi @cgsaxner 
Thank you for your reply .
This plugin can work in Unity 2020. it didn't work in the last time because this plugin compiled by VS 2019 ver16.07 is incompatible with Hololense App compiled by VS 2019 ver16.10. When I use the same version of  VS2019 in plugin and app, It can work well.

I have another question about the transform of  PVtoWorld . what is the origin of the world coordinate system ? How to determine the origin of the world coordinate system ？ Does the origin change every time you start the plugin ?
