### ISSUE TITLE
Adding IMU Capability 

### ISSUE THREAD

**Issue by Sayoj** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#2]
Hi everybody!

I tried to add the IMU capability to the program. 
It should work fine as far as I know, but I can't validate since I don't know how to adapt the python script to streaming the IMU data. 

Any tips or hints for the c++ as well as python part are appreciated. 

Is IMU actually planned by @cgsaxner?

Best Regards

**Comment by cgsaxner** [comment]
Hi! 
I don't work with the IMU data currently, so while at some point I want to include it in the Streamer, it will take some time.

Concerning the C++ part, the [SensorVisualization](https://github.com/microsoft/HoloLens2ForCV/tree/main/Samples/SensorVisualization) example in the HoloLens2ForCV repo contains code on how to access and process the IMU data. It should be relatively straight forward to include the access to the IMU streams in the `HL2Stream::InitializeResearchModeSensors()` and `HL2Stream::InitializeResearchModeProcessing()` functions in the C++ Plugin. Then, you would probably need to create an adapted `Streamer` class (inheriting from the `IResearchModeFrameSink`), in which the `Streamer::Send(...)` function is able to handle an IMU frame and send the data you need to the TCP socket on a separate port. This, you should be able to pass to the `ResearchModeFrameProcessor`.

About the python part, first, you would need to add the header and header format of the data you're sending. The header format basically tells the receiver how many bytes to expect per frame, so this has to correspond to whatever you are sending in the streamer on the C++ side. Then in the header, you basically define the variable names in which the data will be unpacked. So in example in the `VIDEO_FRAME_STREAM_HEADER_FORMAT`, the `q` corresponds to a long long, which will be mapped to the `Timestamp`.  You can check the [Python Struct Doc](https://docs.python.org/2/library/struct.html#format-characters) to find out which format characters map to which data type. Then, create a new IMU receiver inheriting from the `FrameReceiverThread` class. The `FrameReceiverThread` currently expects a header + the image data, so you would have to adapt that. probably it is sufficient to only receive the header for the IMU data.

Hope this could help a bit!

**Comment by Sayoj** [comment]
Thanks for the quick reply! I'll look into it asap
