### ISSUE TITLE
Hololens2 Receives The Detection Result From Server

### ISSUE THREAD

**Issue by sysu17364029** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#5]
Hi @cgsaxner ! Thank you so much for your project, it helps a lot ! 
I'm trying to use YOLO to detect the received frames. I can display the detection result on the server(my computer) now. But I hope to send back the detection result to Hololens2. I add a test code in 'hololens2_simpleclient.py' like the following :
` while True:
        if np.any(video_receiver.latest_frame) :
            result_img, formatBoxes = detection(video_receiver.latest_frame)
            #video_receiver.socket.send(formatBoxes.encode('utf8'))
            video_receiver.socket.send(b'test')
            cv2.imshow('Result', result_img)`
I also add something at the end of the 'SendFram()' function of  'VideoCameraStreamer.cpp' :
`IInputStream response = m_streamSocket.InputStream();
    printf("%s", response);
    if (response)
    {
        OutputDebugStringW(L"Received!\n");
    }`
I don't know if it works or how to test it. I'm new in such kind of coding, so I really need some help.
Looking forward to your reply.

**Comment by shoukailiang** [comment]
hi, @sysu17364029 .i also meet this problems.did you solve it?
