### ISSUE TITLE
Accuracy of the point cloud

### ISSUE THREAD

**Issue by Bornblack** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#7]
Hi @cgsaxner ! 
Thanks for your great work! Have you noticed the misalignment between the point cloud created from the depth camera (AHAT or LT mode)  and the real object ? The mismatch is quit annoying as I want to use the point cloud data to localize the real object. 
I have never accessed the HoloLens 1 device before. Does the HoloLens 1 have the problem?

**Comment by cgsaxner** [comment]
Hi @Bornblack,
yes, I have noticed a lot of misalignment issues with the HoloLens 2. 

I had the impression that the on-board extrinsic calibration of the HoloLens is off, in example between depth camera and video camera, which causes colored point clouds to be off (I opened an [issue](https://github.com/microsoft/HoloLens2ForCV/issues/43) about this in the official HoloLens2ForCV repo, but so far, no solution). But, this offset could probably also result from a misalignment from depth data with the real environment, however I did not test this yet. 
I also noticed that the on-board calibration between the environmental understanding cameras was off, this is why I thought the same problem is causing the issues with depth. For the environmental understanding cameras, I calibrated them myself. But for depth, I have not been successful in obtaining a good calibration so far to investigate this further.

I was also working with the research mode sensors of the HoloLens 1 a lot, and I never experienced such issues there!

**Comment by Bornblack** [comment]
Thanks for your reply . 
I have tried to visualize the point cloud (just depth) on HoloLens 2 directly, and I find that the point cloud  aligns the wall well actually ( see the images below). That's the situation for the simple plane object . When It comes to a complicated surface like face of human, the point cloud is always under the surface.
I think it is not the extrinsic calibration issue that causes the misalignment of the point cloud with the real environment. 
It seems to be the defect of the depth camera itself.

The on-board calibration issue you mentioned helps a lot!

![20210421_091810_HoloLens](https://user-images.githubusercontent.com/49244832/115483198-e8cb0700-a282-11eb-924e-8aa764da9ff1.jpg)
![20210421_091838_HoloLens](https://user-images.githubusercontent.com/49244832/115483204-eb2d6100-a282-11eb-8aad-1265e97480e5.jpg)

**Comment by Lancename** [comment]
@cgsaxner  Hello, I want to get the world coordinate point of a certain color pixel. I originally wanted to get it by matching the depth image and using the space conversion matrix. However, I also encountered the problem you mentioned, and it seems that there is no suitable answer yet. I don’t know if there are other ways to get the world coordinates of a color pixel besides this method?

**Comment by cgsaxner** [comment]
Closing this issue, as it is not an issue with the Plugin, but rather the HoloLens itself.
