### ISSUE TITLE
how to get undistorted depth image

### ISSUE THREAD

**Issue by Lancename** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#8]
Hello, I tried to use the officially recommended look-up table method to obtain the camera coordinates of a certain depth image pixel, but a problem occurred. I found that the depth image obtained in streamrecord.sln is polygonal (seems to be distorted), but the one obtained in this plug-in is circular (distorted). I read the code of stramrecord, but I don't seem to see any additional correction processing on the depth data. How do i proceed

**Comment by Lancename** [comment]
And, I noticed that we seem to limit the maximum depth of 4090 in the plug-in, but the reception at the computer seems to be much larger than 4090

**Comment by Lancename** [comment]
![image](https://user-images.githubusercontent.com/24515772/116482533-ed617200-a8b7-11eb-8362-237f4fb15f03.png)

**Comment by Lancename** [comment]
I am very confused, why the depth resolution of this streamrecorder is 288x320, while the plug-in resolution is 512x512? Looking forward to your reply, thank you very much

**Comment by cgsaxner** [comment]
Hi @Lancename,

I assume you refer to the StreamRecorder from the official [HoloLens2ForCV](https://github.com/microsoft/HoloLens2ForCV/tree/main/Samples/StreamRecorder) repository.
What depth frames are you looking at? It looks to me like the polygonal 288x320 frames are the ones found in the pinhole_projection folder created by the `process_all.py` in the HoloLens2ForCV repo. As far as I know, these are the depth pixels, mapped to a virtual pinhole camera, but you would have to check the code / docs there. 

The "raw", short throw depth frames should be in the Depth AHaT folder, and they should be identical to the frames obtained with this plugin.

**Comment by Lancename** [comment]
![image](https://user-images.githubusercontent.com/24515772/116512973-777efa00-a8fb-11eb-8604-14fbada544fa.png)
![image](https://user-images.githubusercontent.com/24515772/116513113-ac8b4c80-a8fb-11eb-901a-e62174bceb21.png)
Thank you for your prompt reply, I don’t know how to deal with it anymore. I checked the number of Depth Long Throw_lut.bin and the resolution of the original file .pgm (cv.imread in python), and found that the corresponding format is 288x320. I am particularly puzzled now.

**Comment by Lancename** [comment]
![image](https://user-images.githubusercontent.com/24515772/116514375-84045200-a8fd-11eb-85ef-2ecdb158f9db.png)
And I can't understand how effective the official look-up table method is. In the issue of the official project, some people also mentioned that the matching result is not ideal. In SteamRecord, uv-xy can be matched by calling the corresponding function, but it uses z = 1.0f to obtain the corresponding look-up table parameters.

**Comment by Lancename** [comment]
![image](https://user-images.githubusercontent.com/24515772/116515877-74860880-a8ff-11eb-9408-43d82417ea47.png)
I loaded an original look-up table, Depth Long Throw_lut.bin (not processed offline), and checked the number inside, and found that it was indeed 288*320

**Comment by cgsaxner** [comment]
Okay I see now, you are looking at the **Long throw depth** data! The HoloLens 2 delivers two kinds of depth streaming modes as also described [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/research-mode), one for **short throw** (also called Articulated Hand Tracking mode or **AHaT**, reaches up to approximately 1 m) and one for **Long throw** (for longer distances). 

I have never used the long throw depth data myself, but just checked and you are right, the long throw frames have a resolution of 288x320. Currently, the plug-in **only supports streaming of AHaT depth** frames which have a resolution of 512x512. The official StreamRecorder supports both, you can specify in the `AppMain.cpp` which sensors to enable. However, as far as I know, you can only enable one depth streaming mode at a time, so either AHaT or long throw. 

So, to get the same type of frames from the plug-in and the recorder, depending on what kind of data you actually need (short or long distance), you have to either specify in the StreamRecorder that you want AHaT frames (easy), or modify the plug-in to stream the long throw data (probably requires more work).

**Comment by Lancename** [comment]
Thank you very much for your kind help, I also read this article. Although I realized that this may be the problem, and modified your code (only one place), it didn't work. It seems very likely that I did not modify your code correctly. I try to modify the code of SreamRecord. Thank you so much! ! !

**Comment by Lancename** [comment]
Hi@cgsaxner , 
So excited, with your help, this problem has been solved. In addition, I found a small bug in the project. As I mentioned earlier, there seems to be a problem with the depth image data (>maxvalue = 4096). I noticed that this is caused by the inconsistency between the order of depthByeData.push_back and numpy.frombuffer in Flugin. Just reverse the order of the two lines of code as shown in the figure. You can see that the effect of the depth image is very good.
![image](https://user-images.githubusercontent.com/24515772/116670701-a1572000-a9d2-11eb-9f17-354fbd269e23.png)

![image](https://user-images.githubusercontent.com/24515772/116670059-de6ee280-a9d1-11eb-885b-b21a6079be7a.png)
